# Site settings
title: maztek
paginate: 3
paginate_path: "/blog/:num"

# URL
baseurl: ""
url: "http://maztek.io"

# Accounts
email:   miles@maztek.io
twitter: mileszim
github:  jekyll


# Build settings
markdown:  kramdown
permalink: pretty
highlighter: true