# Site settings
title: maztek

# URL
baseurl: ""
url: "http://maztek.io"

# Accounts
email:   miles@maztek.io
twitter: mileszim
github:  jekyll


# Build settings
markdown:  kramdown
permalink: pretty